// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: client.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Obscura v2 Client Protocol
// Unified client-to-client message format for all v2 operations.
// This is the payload inside EncryptedMessage.content - server never sees it.
//
// See: docs/protocol-spec.md, docs/identity.md

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Ephemeral signal kinds — transient real-time presence for a model context.
nonisolated enum Obscura_V2_SignalKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case typing // = 1
  case stoppedTyping // = 2
  case read // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .typing
    case 2: self = .stoppedTyping
    case 3: self = .read
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .typing: return 1
    case .stoppedTyping: return 2
    case .read: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Obscura_V2_SignalKind] = [
    .unspecified,
    .typing,
    .stoppedTyping,
    .read,
  ]

}

nonisolated struct Obscura_V2_EncryptedMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Obscura_V2_EncryptedMessage.TypeEnum = .unspecified

  var content: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum TypeEnum: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case prekeyMessage // = 1
    case encryptedMessage // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .prekeyMessage
      case 2: self = .encryptedMessage
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .prekeyMessage: return 1
      case .encryptedMessage: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Obscura_V2_EncryptedMessage.TypeEnum] = [
      .unspecified,
      .prekeyMessage,
      .encryptedMessage,
    ]

  }

  init() {}
}

nonisolated struct Obscura_V2_ClientMessage: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Obscura_V2_ClientMessage.TypeEnum {
    get {_storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  var timestamp: UInt64 {
    get {_storage._timestamp}
    set {_uniqueStorage()._timestamp = newValue}
  }

  /// Base messaging
  var text: String {
    get {_storage._text}
    set {_uniqueStorage()._text = newValue}
  }

  var mimeType: String {
    get {_storage._mimeType}
    set {_uniqueStorage()._mimeType = newValue}
  }

  var displayDuration: UInt32 {
    get {_storage._displayDuration}
    set {_uniqueStorage()._displayDuration = newValue}
  }

  /// Attachment reference (replaces inline image_data)
  var attachmentID: String {
    get {_storage._attachmentID}
    set {_uniqueStorage()._attachmentID = newValue}
  }

  var attachmentExpires: UInt64 {
    get {_storage._attachmentExpires}
    set {_uniqueStorage()._attachmentExpires = newValue}
  }

  /// Friend request/response
  var username: String {
    get {_storage._username}
    set {_uniqueStorage()._username = newValue}
  }

  var accepted: Bool {
    get {_storage._accepted}
    set {_uniqueStorage()._accepted = newValue}
  }

  /// Session reset
  var resetReason: String {
    get {_storage._resetReason}
    set {_uniqueStorage()._resetReason = newValue}
  }

  /// Device management payloads
  var deviceLinkApproval: Obscura_V2_DeviceLinkApproval {
    get {_storage._deviceLinkApproval ?? Obscura_V2_DeviceLinkApproval()}
    set {_uniqueStorage()._deviceLinkApproval = newValue}
  }
  /// Returns true if `deviceLinkApproval` has been explicitly set.
  var hasDeviceLinkApproval: Bool {_storage._deviceLinkApproval != nil}
  /// Clears the value of `deviceLinkApproval`. Subsequent reads from it will return its default value.
  mutating func clearDeviceLinkApproval() {_uniqueStorage()._deviceLinkApproval = nil}

  var deviceAnnounce: Obscura_V2_DeviceAnnounce {
    get {_storage._deviceAnnounce ?? Obscura_V2_DeviceAnnounce()}
    set {_uniqueStorage()._deviceAnnounce = newValue}
  }
  /// Returns true if `deviceAnnounce` has been explicitly set.
  var hasDeviceAnnounce: Bool {_storage._deviceAnnounce != nil}
  /// Clears the value of `deviceAnnounce`. Subsequent reads from it will return its default value.
  mutating func clearDeviceAnnounce() {_uniqueStorage()._deviceAnnounce = nil}

  var deviceRecoveryAnnounce: Obscura_V2_DeviceRecoveryAnnounce {
    get {_storage._deviceRecoveryAnnounce ?? Obscura_V2_DeviceRecoveryAnnounce()}
    set {_uniqueStorage()._deviceRecoveryAnnounce = newValue}
  }
  /// Returns true if `deviceRecoveryAnnounce` has been explicitly set.
  var hasDeviceRecoveryAnnounce: Bool {_storage._deviceRecoveryAnnounce != nil}
  /// Clears the value of `deviceRecoveryAnnounce`. Subsequent reads from it will return its default value.
  mutating func clearDeviceRecoveryAnnounce() {_uniqueStorage()._deviceRecoveryAnnounce = nil}

  /// Sync payloads (for new device onboarding)
  var historyChunk: Obscura_V2_HistoryChunk {
    get {_storage._historyChunk ?? Obscura_V2_HistoryChunk()}
    set {_uniqueStorage()._historyChunk = newValue}
  }
  /// Returns true if `historyChunk` has been explicitly set.
  var hasHistoryChunk: Bool {_storage._historyChunk != nil}
  /// Clears the value of `historyChunk`. Subsequent reads from it will return its default value.
  mutating func clearHistoryChunk() {_uniqueStorage()._historyChunk = nil}

  var settingsData: Data {
    get {_storage._settingsData}
    set {_uniqueStorage()._settingsData = newValue}
  }

  var readMessageID: String {
    get {_storage._readMessageID}
    set {_uniqueStorage()._readMessageID = newValue}
  }

  var syncBlob: Obscura_V2_SyncBlob {
    get {_storage._syncBlob ?? Obscura_V2_SyncBlob()}
    set {_uniqueStorage()._syncBlob = newValue}
  }
  /// Returns true if `syncBlob` has been explicitly set.
  var hasSyncBlob: Bool {_storage._syncBlob != nil}
  /// Clears the value of `syncBlob`. Subsequent reads from it will return its default value.
  mutating func clearSyncBlob() {_uniqueStorage()._syncBlob = nil}

  var sentSync: Obscura_V2_SentSync {
    get {_storage._sentSync ?? Obscura_V2_SentSync()}
    set {_uniqueStorage()._sentSync = newValue}
  }
  /// Returns true if `sentSync` has been explicitly set.
  var hasSentSync: Bool {_storage._sentSync != nil}
  /// Clears the value of `sentSync`. Subsequent reads from it will return its default value.
  mutating func clearSentSync() {_uniqueStorage()._sentSync = nil}

  /// Attachment reference (E2E encrypted key sharing)
  var contentReference: Obscura_V2_ContentReference {
    get {_storage._contentReference ?? Obscura_V2_ContentReference()}
    set {_uniqueStorage()._contentReference = newValue}
  }
  /// Returns true if `contentReference` has been explicitly set.
  var hasContentReference: Bool {_storage._contentReference != nil}
  /// Clears the value of `contentReference`. Subsequent reads from it will return its default value.
  mutating func clearContentReference() {_uniqueStorage()._contentReference = nil}

  /// Chunked attachment reference (for large files)
  var chunkedContentReference: Obscura_V2_ChunkedContentReference {
    get {_storage._chunkedContentReference ?? Obscura_V2_ChunkedContentReference()}
    set {_uniqueStorage()._chunkedContentReference = newValue}
  }
  /// Returns true if `chunkedContentReference` has been explicitly set.
  var hasChunkedContentReference: Bool {_storage._chunkedContentReference != nil}
  /// Clears the value of `chunkedContentReference`. Subsequent reads from it will return its default value.
  mutating func clearChunkedContentReference() {_uniqueStorage()._chunkedContentReference = nil}

  /// ORM Layer payload
  var modelSync: Obscura_V2_ModelSync {
    get {_storage._modelSync ?? Obscura_V2_ModelSync()}
    set {_uniqueStorage()._modelSync = newValue}
  }
  /// Returns true if `modelSync` has been explicitly set.
  var hasModelSync: Bool {_storage._modelSync != nil}
  /// Clears the value of `modelSync`. Subsequent reads from it will return its default value.
  mutating func clearModelSync() {_uniqueStorage()._modelSync = nil}

  /// Ephemeral signal payload (typing, read receipts, presence)
  var modelSignal: Obscura_V2_ModelSignal {
    get {_storage._modelSignal ?? Obscura_V2_ModelSignal()}
    set {_uniqueStorage()._modelSignal = newValue}
  }
  /// Returns true if `modelSignal` has been explicitly set.
  var hasModelSignal: Bool {_storage._modelSignal != nil}
  /// Clears the value of `modelSignal`. Subsequent reads from it will return its default value.
  mutating func clearModelSignal() {_uniqueStorage()._modelSignal = nil}

  /// Friend sync payload
  var friendSync: Obscura_V2_FriendSync {
    get {_storage._friendSync ?? Obscura_V2_FriendSync()}
    set {_uniqueStorage()._friendSync = newValue}
  }
  /// Returns true if `friendSync` has been explicitly set.
  var hasFriendSync: Bool {_storage._friendSync != nil}
  /// Clears the value of `friendSync`. Subsequent reads from it will return its default value.
  mutating func clearFriendSync() {_uniqueStorage()._friendSync = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum TypeEnum: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0

    /// Base messaging (0-9)
    case image // = 1
    case friendRequest // = 2
    case friendResponse // = 3
    case sessionReset // = 4
    case video // = 5
    case audio // = 6

    /// Generic file attachment
    case file // = 7

    /// Was 0; renumbered so 0 can be TYPE_UNSPECIFIED
    case text // = 8

    /// Device management (10-19)
    /// Note: 10 intentionally skipped - link "request" is out-of-band (QR/link code)
    case deviceLinkApproval // = 11
    case deviceAnnounce // = 12

    /// Account recovery - replaces all old devices
    case deviceRecoveryAnnounce // = 13

    /// Sync (20-29)
    case historyChunk // = 20
    case settingsSync // = 21
    case readSync // = 22

    /// Full state transfer (gzipped JSON)
    case syncBlob // = 23

    /// Notify own devices of sent message
    case sentSync // = 24

    /// E2E encrypted attachment key sharing
    case contentReference // = 25

    /// Request full sync from another device
    case syncRequest // = 26

    /// Sync friend changes to own devices
    case friendSync // = 27

    /// Large file (chunked attachment)
    case chunkedContentReference // = 28

    /// ORM Layer (30-39)
    case modelSync // = 30

    /// Ephemeral signal (typing, read receipt) — not persisted
    case modelSignal // = 31
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .image
      case 2: self = .friendRequest
      case 3: self = .friendResponse
      case 4: self = .sessionReset
      case 5: self = .video
      case 6: self = .audio
      case 7: self = .file
      case 8: self = .text
      case 11: self = .deviceLinkApproval
      case 12: self = .deviceAnnounce
      case 13: self = .deviceRecoveryAnnounce
      case 20: self = .historyChunk
      case 21: self = .settingsSync
      case 22: self = .readSync
      case 23: self = .syncBlob
      case 24: self = .sentSync
      case 25: self = .contentReference
      case 26: self = .syncRequest
      case 27: self = .friendSync
      case 28: self = .chunkedContentReference
      case 30: self = .modelSync
      case 31: self = .modelSignal
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .image: return 1
      case .friendRequest: return 2
      case .friendResponse: return 3
      case .sessionReset: return 4
      case .video: return 5
      case .audio: return 6
      case .file: return 7
      case .text: return 8
      case .deviceLinkApproval: return 11
      case .deviceAnnounce: return 12
      case .deviceRecoveryAnnounce: return 13
      case .historyChunk: return 20
      case .settingsSync: return 21
      case .readSync: return 22
      case .syncBlob: return 23
      case .sentSync: return 24
      case .contentReference: return 25
      case .syncRequest: return 26
      case .friendSync: return 27
      case .chunkedContentReference: return 28
      case .modelSync: return 30
      case .modelSignal: return 31
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Obscura_V2_ClientMessage.TypeEnum] = [
      .unspecified,
      .image,
      .friendRequest,
      .friendResponse,
      .sessionReset,
      .video,
      .audio,
      .file,
      .text,
      .deviceLinkApproval,
      .deviceAnnounce,
      .deviceRecoveryAnnounce,
      .historyChunk,
      .settingsSync,
      .readSync,
      .syncBlob,
      .sentSync,
      .contentReference,
      .syncRequest,
      .friendSync,
      .chunkedContentReference,
      .modelSync,
      .modelSignal,
    ]

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Information about a single device
nonisolated struct Obscura_V2_DeviceInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Device UUID (e.g., "550e8400-e29b-41d4...")
  var deviceUuid: String = String()

  /// Server-assigned device UUID
  var deviceID: String = String()

  /// Human-readable name (e.g., "iPhone")
  var deviceName: String = String()

  /// Signal identity public key (33 bytes with 0x05 prefix)
  var signalIdentityKey: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Sent from existing device to new device to complete linking
/// Per identity.md: transfers P2P identity, device list, and optionally data exports
nonisolated struct Obscura_V2_DeviceLinkApproval: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// P2P identity public key (33 bytes - Curve25519 with prefix)
  var p2PPublicKey: Data = Data()

  /// P2P identity private key (32 bytes) - transferred securely
  var p2PPrivateKey: Data = Data()

  /// Recovery public key (32 bytes) for revocation verification
  var recoveryPublicKey: Data = Data()

  /// Echo back challenge from link code
  var challengeResponse: Data = Data()

  /// Complete list of linked devices
  var ownDevices: [Obscura_V2_DeviceInfo] = []

  /// Serialized friend list (optional)
  var friendsExport: Data = Data()

  /// Serialized Signal sessions (optional)
  var sessionsExport: Data = Data()

  /// Serialized trusted identities (optional)
  var trustedIdsExport: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Broadcast to all friends when device list changes
/// Per identity.md: LWW semantics - latest timestamp wins
nonisolated struct Obscura_V2_DeviceAnnounce: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Current complete device list (replaces old list)
  var devices: [Obscura_V2_DeviceInfo] = []

  /// For LWW merge (latest wins)
  var timestamp: UInt64 = 0

  /// True if this removes a device
  var isRevocation: Bool = false

  /// Signed with device key (add) or recovery key (revoke)
  var signature: Data = Data()

  /// For friend to verify future revocation signatures
  var recoveryPublicKey: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Account recovery announcement
/// Sent to friends when recovering from backup
/// Signed with recovery key to prove legitimacy
nonisolated struct Obscura_V2_DeviceRecoveryAnnounce: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// New device list (just the recovery device)
  var newDevices: [Obscura_V2_DeviceInfo] = []

  var timestamp: UInt64 = 0

  /// Signed with recovery key
  var signature: Data = Data()

  /// True if replacing all old devices
  var isFullRecovery: Bool = false

  /// Recovery public key for verification
  var recoveryPublicKey: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Chunk of history sent to new device
nonisolated struct Obscura_V2_HistoryChunk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var entries: [Obscura_V2_MessageEntry] = []

  /// True if this is the last chunk
  var isFinal: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Single message entry for history sync
nonisolated struct Obscura_V2_MessageEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique ID: hash(content + timestamp + author_device)
  var messageID: String = String()

  /// Client timestamp (ms since epoch)
  var timestamp: UInt64 = 0

  /// The actual message payload
  var content: Data = Data()

  /// Which device created this
  var authorDeviceID: Data = Data()

  /// sign(message_id + timestamp + content, device_key)
  var signature: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Full state transfer blob (gzipped JSON)
/// Sent from existing device to new device after link approval
nonisolated struct Obscura_V2_SyncBlob: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// gzip(JSON.stringify({ friends, messages, settings }))
  var compressedData: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Notify own devices of sent message (for incremental sync)
/// Sent to all own devices when a message is sent to a friend
nonisolated struct Obscura_V2_SentSync: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Friend username (who the message was sent to)
  var conversationID: String = String()

  /// Unique message ID
  var messageID: String = String()

  /// When the message was sent
  var timestamp: UInt64 = 0

  /// The message content
  var content: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Sync friend list changes to own devices
/// Sent to all own devices when friend is added or removed
nonisolated struct Obscura_V2_FriendSync: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Friend's username
  var username: String = String()

  /// "add" or "remove"
  var action: String = String()

  /// Friend status (pending, accepted)
  var status: String = String()

  /// Friend's devices (for fan-out)
  var devices: [Obscura_V2_DeviceInfo] = []

  /// When the change occurred
  var timestamp: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Reference to an encrypted attachment
/// The blob is encrypted with AES-256-GCM before upload.
/// This message carries the key to recipients via Signal encryption.
/// Upload once, share key to many.
nonisolated struct Obscura_V2_ContentReference: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Server attachment ID
  var attachmentID: String = String()

  /// AES-256-GCM key (32 bytes)
  var contentKey: Data = Data()

  /// AES-GCM nonce (12 bytes)
  var nonce: Data = Data()

  /// SHA-256 of plaintext for integrity
  var contentHash: Data = Data()

  /// MIME type (e.g., "image/jpeg")
  var contentType: String = String()

  /// Original size for progress/preview
  var sizeBytes: UInt64 = 0

  /// Original filename for file attachments
  var fileName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Reference to a chunked large file (>950KB, up to 100MB)
/// Each chunk is encrypted separately with its own key
nonisolated struct Obscura_V2_ChunkedContentReference: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique ID for the entire file
  var fileID: String = String()

  /// Ordered list of chunk references
  var chunks: [Obscura_V2_ChunkInfo] = []

  /// SHA-256 of reassembled plaintext
  var completeHash: Data = Data()

  /// MIME type
  var contentType: String = String()

  /// Total file size
  var totalSizeBytes: UInt64 = 0

  /// Original filename
  var fileName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Single chunk within a chunked file
nonisolated struct Obscura_V2_ChunkInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Chunk position (0-based)
  var index: UInt32 = 0

  /// Server attachment ID for this chunk
  var attachmentID: String = String()

  /// AES-256-GCM key (32 bytes)
  var contentKey: Data = Data()

  /// AES-GCM nonce (12 bytes)
  var nonce: Data = Data()

  /// SHA-256 of this chunk's plaintext
  var chunkHash: Data = Data()

  /// Size of this chunk
  var sizeBytes: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// CRDT model sync operation
/// Sent between devices to synchronize model state (stories, streaks, etc.)
/// Uses existing fan-out + self-sync patterns from Level 2
nonisolated struct Obscura_V2_ModelSync: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Model name: "story", "streak", "settings"
  var model: String = String()

  /// Entry ID: "story_1706389200_abc123"
  var id: String = String()

  /// Operation type
  var op: Obscura_V2_ModelSync.Op = .unspecified

  /// Lamport timestamp for CRDT ordering
  var timestamp: UInt64 = 0

  /// JSON-encoded model data
  var data: Data = Data()

  /// sign(model + id + data + timestamp, deviceKey)
  var signature: Data = Data()

  /// Which device created this entry
  var authorDeviceID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum Op: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0

    /// Only for LWW models
    case update // = 1

    /// Soft delete (tombstone)
    case delete // = 2

    /// Was 0; renumbered so 0 can be OP_UNSPECIFIED
    case create // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .update
      case 2: self = .delete
      case 3: self = .create
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .update: return 1
      case .delete: return 2
      case .create: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Obscura_V2_ModelSync.Op] = [
      .unspecified,
      .update,
      .delete,
      .create,
    ]

  }

  init() {}
}

/// Ephemeral model signal — real-time presence attached to a model context.
/// Not persisted, not CRDT-merged; in-memory only, auto-expires. The sender's
/// identity and the timestamp come from the authenticated ClientMessage envelope,
/// so they are intentionally NOT duplicated here.
nonisolated struct Obscura_V2_ModelSignal: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Model namespace, e.g. "directMessage"
  var model: String = String()

  /// Which transient state
  var kind: Obscura_V2_SignalKind = .unspecified

  /// Context the signal applies to (e.g. the conversation id)
  var contextID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "obscura.v2"

extension Obscura_V2_SignalKind: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SIGNAL_KIND_UNSPECIFIED\0\u{1}SIGNAL_KIND_TYPING\0\u{1}SIGNAL_KIND_STOPPED_TYPING\0\u{1}SIGNAL_KIND_READ\0")
}

extension Obscura_V2_EncryptedMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EncryptedMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}content\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.content) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != .unspecified {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularBytesField(value: self.content, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_EncryptedMessage, rhs: Obscura_V2_EncryptedMessage) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_EncryptedMessage.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TYPE_UNSPECIFIED\0\u{1}TYPE_PREKEY_MESSAGE\0\u{1}TYPE_ENCRYPTED_MESSAGE\0")
}

extension Obscura_V2_ClientMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ClientMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}timestamp\0\u{2}\u{8}text\0\u{3}mime_type\0\u{3}display_duration\0\u{4}\u{3}attachment_id\0\u{3}attachment_expires\0\u{2}\u{4}username\0\u{1}accepted\0\u{4}\u{4}reset_reason\0\u{4}\u{5}device_link_approval\0\u{3}device_announce\0\u{3}device_recovery_announce\0\u{4}\u{8}history_chunk\0\u{3}settings_data\0\u{3}read_message_id\0\u{3}sync_blob\0\u{3}sent_sync\0\u{3}content_reference\0\u{3}chunked_content_reference\0\u{4}\u{4}model_sync\0\u{3}friend_sync\0\u{3}model_signal\0")

  fileprivate class _StorageClass {
    var _type: Obscura_V2_ClientMessage.TypeEnum = .unspecified
    var _timestamp: UInt64 = 0
    var _text: String = String()
    var _mimeType: String = String()
    var _displayDuration: UInt32 = 0
    var _attachmentID: String = String()
    var _attachmentExpires: UInt64 = 0
    var _username: String = String()
    var _accepted: Bool = false
    var _resetReason: String = String()
    var _deviceLinkApproval: Obscura_V2_DeviceLinkApproval? = nil
    var _deviceAnnounce: Obscura_V2_DeviceAnnounce? = nil
    var _deviceRecoveryAnnounce: Obscura_V2_DeviceRecoveryAnnounce? = nil
    var _historyChunk: Obscura_V2_HistoryChunk? = nil
    var _settingsData: Data = Data()
    var _readMessageID: String = String()
    var _syncBlob: Obscura_V2_SyncBlob? = nil
    var _sentSync: Obscura_V2_SentSync? = nil
    var _contentReference: Obscura_V2_ContentReference? = nil
    var _chunkedContentReference: Obscura_V2_ChunkedContentReference? = nil
    var _modelSync: Obscura_V2_ModelSync? = nil
    var _modelSignal: Obscura_V2_ModelSignal? = nil
    var _friendSync: Obscura_V2_FriendSync? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _type = source._type
      _timestamp = source._timestamp
      _text = source._text
      _mimeType = source._mimeType
      _displayDuration = source._displayDuration
      _attachmentID = source._attachmentID
      _attachmentExpires = source._attachmentExpires
      _username = source._username
      _accepted = source._accepted
      _resetReason = source._resetReason
      _deviceLinkApproval = source._deviceLinkApproval
      _deviceAnnounce = source._deviceAnnounce
      _deviceRecoveryAnnounce = source._deviceRecoveryAnnounce
      _historyChunk = source._historyChunk
      _settingsData = source._settingsData
      _readMessageID = source._readMessageID
      _syncBlob = source._syncBlob
      _sentSync = source._sentSync
      _contentReference = source._contentReference
      _chunkedContentReference = source._chunkedContentReference
      _modelSync = source._modelSync
      _modelSignal = source._modelSignal
      _friendSync = source._friendSync
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularEnumField(value: &_storage._type) }()
        case 2: try { try decoder.decodeSingularUInt64Field(value: &_storage._timestamp) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._text) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._mimeType) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._displayDuration) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._attachmentID) }()
        case 16: try { try decoder.decodeSingularUInt64Field(value: &_storage._attachmentExpires) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._username) }()
        case 21: try { try decoder.decodeSingularBoolField(value: &_storage._accepted) }()
        case 25: try { try decoder.decodeSingularStringField(value: &_storage._resetReason) }()
        case 30: try { try decoder.decodeSingularMessageField(value: &_storage._deviceLinkApproval) }()
        case 31: try { try decoder.decodeSingularMessageField(value: &_storage._deviceAnnounce) }()
        case 32: try { try decoder.decodeSingularMessageField(value: &_storage._deviceRecoveryAnnounce) }()
        case 40: try { try decoder.decodeSingularMessageField(value: &_storage._historyChunk) }()
        case 41: try { try decoder.decodeSingularBytesField(value: &_storage._settingsData) }()
        case 42: try { try decoder.decodeSingularStringField(value: &_storage._readMessageID) }()
        case 43: try { try decoder.decodeSingularMessageField(value: &_storage._syncBlob) }()
        case 44: try { try decoder.decodeSingularMessageField(value: &_storage._sentSync) }()
        case 45: try { try decoder.decodeSingularMessageField(value: &_storage._contentReference) }()
        case 46: try { try decoder.decodeSingularMessageField(value: &_storage._chunkedContentReference) }()
        case 50: try { try decoder.decodeSingularMessageField(value: &_storage._modelSync) }()
        case 51: try { try decoder.decodeSingularMessageField(value: &_storage._friendSync) }()
        case 52: try { try decoder.decodeSingularMessageField(value: &_storage._modelSignal) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._type != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._type, fieldNumber: 1)
      }
      if _storage._timestamp != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._timestamp, fieldNumber: 2)
      }
      if !_storage._text.isEmpty {
        try visitor.visitSingularStringField(value: _storage._text, fieldNumber: 10)
      }
      if !_storage._mimeType.isEmpty {
        try visitor.visitSingularStringField(value: _storage._mimeType, fieldNumber: 11)
      }
      if _storage._displayDuration != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._displayDuration, fieldNumber: 12)
      }
      if !_storage._attachmentID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._attachmentID, fieldNumber: 15)
      }
      if _storage._attachmentExpires != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._attachmentExpires, fieldNumber: 16)
      }
      if !_storage._username.isEmpty {
        try visitor.visitSingularStringField(value: _storage._username, fieldNumber: 20)
      }
      if _storage._accepted != false {
        try visitor.visitSingularBoolField(value: _storage._accepted, fieldNumber: 21)
      }
      if !_storage._resetReason.isEmpty {
        try visitor.visitSingularStringField(value: _storage._resetReason, fieldNumber: 25)
      }
      try { if let v = _storage._deviceLinkApproval {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 30)
      } }()
      try { if let v = _storage._deviceAnnounce {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 31)
      } }()
      try { if let v = _storage._deviceRecoveryAnnounce {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 32)
      } }()
      try { if let v = _storage._historyChunk {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 40)
      } }()
      if !_storage._settingsData.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._settingsData, fieldNumber: 41)
      }
      if !_storage._readMessageID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._readMessageID, fieldNumber: 42)
      }
      try { if let v = _storage._syncBlob {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 43)
      } }()
      try { if let v = _storage._sentSync {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 44)
      } }()
      try { if let v = _storage._contentReference {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 45)
      } }()
      try { if let v = _storage._chunkedContentReference {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 46)
      } }()
      try { if let v = _storage._modelSync {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 50)
      } }()
      try { if let v = _storage._friendSync {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 51)
      } }()
      try { if let v = _storage._modelSignal {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 52)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_ClientMessage, rhs: Obscura_V2_ClientMessage) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._type != rhs_storage._type {return false}
        if _storage._timestamp != rhs_storage._timestamp {return false}
        if _storage._text != rhs_storage._text {return false}
        if _storage._mimeType != rhs_storage._mimeType {return false}
        if _storage._displayDuration != rhs_storage._displayDuration {return false}
        if _storage._attachmentID != rhs_storage._attachmentID {return false}
        if _storage._attachmentExpires != rhs_storage._attachmentExpires {return false}
        if _storage._username != rhs_storage._username {return false}
        if _storage._accepted != rhs_storage._accepted {return false}
        if _storage._resetReason != rhs_storage._resetReason {return false}
        if _storage._deviceLinkApproval != rhs_storage._deviceLinkApproval {return false}
        if _storage._deviceAnnounce != rhs_storage._deviceAnnounce {return false}
        if _storage._deviceRecoveryAnnounce != rhs_storage._deviceRecoveryAnnounce {return false}
        if _storage._historyChunk != rhs_storage._historyChunk {return false}
        if _storage._settingsData != rhs_storage._settingsData {return false}
        if _storage._readMessageID != rhs_storage._readMessageID {return false}
        if _storage._syncBlob != rhs_storage._syncBlob {return false}
        if _storage._sentSync != rhs_storage._sentSync {return false}
        if _storage._contentReference != rhs_storage._contentReference {return false}
        if _storage._chunkedContentReference != rhs_storage._chunkedContentReference {return false}
        if _storage._modelSync != rhs_storage._modelSync {return false}
        if _storage._modelSignal != rhs_storage._modelSignal {return false}
        if _storage._friendSync != rhs_storage._friendSync {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_ClientMessage.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TYPE_UNSPECIFIED\0\u{1}TYPE_IMAGE\0\u{1}TYPE_FRIEND_REQUEST\0\u{1}TYPE_FRIEND_RESPONSE\0\u{1}TYPE_SESSION_RESET\0\u{1}TYPE_VIDEO\0\u{1}TYPE_AUDIO\0\u{1}TYPE_FILE\0\u{1}TYPE_TEXT\0\u{2}\u{3}TYPE_DEVICE_LINK_APPROVAL\0\u{1}TYPE_DEVICE_ANNOUNCE\0\u{1}TYPE_DEVICE_RECOVERY_ANNOUNCE\0\u{2}\u{7}TYPE_HISTORY_CHUNK\0\u{1}TYPE_SETTINGS_SYNC\0\u{1}TYPE_READ_SYNC\0\u{1}TYPE_SYNC_BLOB\0\u{1}TYPE_SENT_SYNC\0\u{1}TYPE_CONTENT_REFERENCE\0\u{1}TYPE_SYNC_REQUEST\0\u{1}TYPE_FRIEND_SYNC\0\u{1}TYPE_CHUNKED_CONTENT_REFERENCE\0\u{2}\u{2}TYPE_MODEL_SYNC\0\u{1}TYPE_MODEL_SIGNAL\0")
}

extension Obscura_V2_DeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeviceInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_uuid\0\u{3}device_id\0\u{3}device_name\0\u{3}signal_identity_key\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceUuid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.deviceName) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.signalIdentityKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceUuid.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceUuid, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 2)
    }
    if !self.deviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceName, fieldNumber: 3)
    }
    if !self.signalIdentityKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.signalIdentityKey, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_DeviceInfo, rhs: Obscura_V2_DeviceInfo) -> Bool {
    if lhs.deviceUuid != rhs.deviceUuid {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.deviceName != rhs.deviceName {return false}
    if lhs.signalIdentityKey != rhs.signalIdentityKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_DeviceLinkApproval: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeviceLinkApproval"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}p2p_public_key\0\u{3}p2p_private_key\0\u{3}recovery_public_key\0\u{3}challenge_response\0\u{3}own_devices\0\u{3}friends_export\0\u{3}sessions_export\0\u{3}trusted_ids_export\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.p2PPublicKey) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.p2PPrivateKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.recoveryPublicKey) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.challengeResponse) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.ownDevices) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.friendsExport) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.sessionsExport) }()
      case 8: try { try decoder.decodeSingularBytesField(value: &self.trustedIdsExport) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.p2PPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.p2PPublicKey, fieldNumber: 1)
    }
    if !self.p2PPrivateKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.p2PPrivateKey, fieldNumber: 2)
    }
    if !self.recoveryPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.recoveryPublicKey, fieldNumber: 3)
    }
    if !self.challengeResponse.isEmpty {
      try visitor.visitSingularBytesField(value: self.challengeResponse, fieldNumber: 4)
    }
    if !self.ownDevices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.ownDevices, fieldNumber: 5)
    }
    if !self.friendsExport.isEmpty {
      try visitor.visitSingularBytesField(value: self.friendsExport, fieldNumber: 6)
    }
    if !self.sessionsExport.isEmpty {
      try visitor.visitSingularBytesField(value: self.sessionsExport, fieldNumber: 7)
    }
    if !self.trustedIdsExport.isEmpty {
      try visitor.visitSingularBytesField(value: self.trustedIdsExport, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_DeviceLinkApproval, rhs: Obscura_V2_DeviceLinkApproval) -> Bool {
    if lhs.p2PPublicKey != rhs.p2PPublicKey {return false}
    if lhs.p2PPrivateKey != rhs.p2PPrivateKey {return false}
    if lhs.recoveryPublicKey != rhs.recoveryPublicKey {return false}
    if lhs.challengeResponse != rhs.challengeResponse {return false}
    if lhs.ownDevices != rhs.ownDevices {return false}
    if lhs.friendsExport != rhs.friendsExport {return false}
    if lhs.sessionsExport != rhs.sessionsExport {return false}
    if lhs.trustedIdsExport != rhs.trustedIdsExport {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_DeviceAnnounce: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeviceAnnounce"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}devices\0\u{1}timestamp\0\u{3}is_revocation\0\u{1}signature\0\u{3}recovery_public_key\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.devices) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isRevocation) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.recoveryPublicKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.devices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.devices, fieldNumber: 1)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 2)
    }
    if self.isRevocation != false {
      try visitor.visitSingularBoolField(value: self.isRevocation, fieldNumber: 3)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 4)
    }
    if !self.recoveryPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.recoveryPublicKey, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_DeviceAnnounce, rhs: Obscura_V2_DeviceAnnounce) -> Bool {
    if lhs.devices != rhs.devices {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.isRevocation != rhs.isRevocation {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.recoveryPublicKey != rhs.recoveryPublicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_DeviceRecoveryAnnounce: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeviceRecoveryAnnounce"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}new_devices\0\u{1}timestamp\0\u{1}signature\0\u{3}is_full_recovery\0\u{3}recovery_public_key\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.newDevices) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isFullRecovery) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.recoveryPublicKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.newDevices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.newDevices, fieldNumber: 1)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 2)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 3)
    }
    if self.isFullRecovery != false {
      try visitor.visitSingularBoolField(value: self.isFullRecovery, fieldNumber: 4)
    }
    if !self.recoveryPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.recoveryPublicKey, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_DeviceRecoveryAnnounce, rhs: Obscura_V2_DeviceRecoveryAnnounce) -> Bool {
    if lhs.newDevices != rhs.newDevices {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.isFullRecovery != rhs.isFullRecovery {return false}
    if lhs.recoveryPublicKey != rhs.recoveryPublicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_HistoryChunk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HistoryChunk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entries\0\u{3}is_final\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isFinal) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 1)
    }
    if self.isFinal != false {
      try visitor.visitSingularBoolField(value: self.isFinal, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_HistoryChunk, rhs: Obscura_V2_HistoryChunk) -> Bool {
    if lhs.entries != rhs.entries {return false}
    if lhs.isFinal != rhs.isFinal {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_MessageEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MessageEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}message_id\0\u{1}timestamp\0\u{1}content\0\u{3}author_device_id\0\u{1}signature\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.messageID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.content) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.authorDeviceID) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.messageID.isEmpty {
      try visitor.visitSingularStringField(value: self.messageID, fieldNumber: 1)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 2)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularBytesField(value: self.content, fieldNumber: 3)
    }
    if !self.authorDeviceID.isEmpty {
      try visitor.visitSingularBytesField(value: self.authorDeviceID, fieldNumber: 4)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_MessageEntry, rhs: Obscura_V2_MessageEntry) -> Bool {
    if lhs.messageID != rhs.messageID {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.content != rhs.content {return false}
    if lhs.authorDeviceID != rhs.authorDeviceID {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_SyncBlob: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SyncBlob"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}compressed_data\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.compressedData) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.compressedData.isEmpty {
      try visitor.visitSingularBytesField(value: self.compressedData, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_SyncBlob, rhs: Obscura_V2_SyncBlob) -> Bool {
    if lhs.compressedData != rhs.compressedData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_SentSync: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SentSync"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}conversation_id\0\u{3}message_id\0\u{1}timestamp\0\u{1}content\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.conversationID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.messageID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.content) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.conversationID.isEmpty {
      try visitor.visitSingularStringField(value: self.conversationID, fieldNumber: 1)
    }
    if !self.messageID.isEmpty {
      try visitor.visitSingularStringField(value: self.messageID, fieldNumber: 2)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 3)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularBytesField(value: self.content, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_SentSync, rhs: Obscura_V2_SentSync) -> Bool {
    if lhs.conversationID != rhs.conversationID {return false}
    if lhs.messageID != rhs.messageID {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_FriendSync: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FriendSync"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}username\0\u{1}action\0\u{1}status\0\u{1}devices\0\u{1}timestamp\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.username) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.action) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.devices) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.username.isEmpty {
      try visitor.visitSingularStringField(value: self.username, fieldNumber: 1)
    }
    if !self.action.isEmpty {
      try visitor.visitSingularStringField(value: self.action, fieldNumber: 2)
    }
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 3)
    }
    if !self.devices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.devices, fieldNumber: 4)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_FriendSync, rhs: Obscura_V2_FriendSync) -> Bool {
    if lhs.username != rhs.username {return false}
    if lhs.action != rhs.action {return false}
    if lhs.status != rhs.status {return false}
    if lhs.devices != rhs.devices {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_ContentReference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ContentReference"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}attachment_id\0\u{3}content_key\0\u{1}nonce\0\u{3}content_hash\0\u{3}content_type\0\u{3}size_bytes\0\u{3}file_name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.attachmentID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.contentKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.nonce) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.contentHash) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.contentType) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.sizeBytes) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.fileName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.attachmentID.isEmpty {
      try visitor.visitSingularStringField(value: self.attachmentID, fieldNumber: 1)
    }
    if !self.contentKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.contentKey, fieldNumber: 2)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.nonce, fieldNumber: 3)
    }
    if !self.contentHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.contentHash, fieldNumber: 4)
    }
    if !self.contentType.isEmpty {
      try visitor.visitSingularStringField(value: self.contentType, fieldNumber: 5)
    }
    if self.sizeBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.sizeBytes, fieldNumber: 6)
    }
    if !self.fileName.isEmpty {
      try visitor.visitSingularStringField(value: self.fileName, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_ContentReference, rhs: Obscura_V2_ContentReference) -> Bool {
    if lhs.attachmentID != rhs.attachmentID {return false}
    if lhs.contentKey != rhs.contentKey {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.contentHash != rhs.contentHash {return false}
    if lhs.contentType != rhs.contentType {return false}
    if lhs.sizeBytes != rhs.sizeBytes {return false}
    if lhs.fileName != rhs.fileName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_ChunkedContentReference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ChunkedContentReference"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}file_id\0\u{1}chunks\0\u{3}complete_hash\0\u{3}content_type\0\u{3}total_size_bytes\0\u{3}file_name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.fileID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.chunks) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.completeHash) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.contentType) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.totalSizeBytes) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.fileName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileID.isEmpty {
      try visitor.visitSingularStringField(value: self.fileID, fieldNumber: 1)
    }
    if !self.chunks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.chunks, fieldNumber: 2)
    }
    if !self.completeHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.completeHash, fieldNumber: 3)
    }
    if !self.contentType.isEmpty {
      try visitor.visitSingularStringField(value: self.contentType, fieldNumber: 4)
    }
    if self.totalSizeBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.totalSizeBytes, fieldNumber: 5)
    }
    if !self.fileName.isEmpty {
      try visitor.visitSingularStringField(value: self.fileName, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_ChunkedContentReference, rhs: Obscura_V2_ChunkedContentReference) -> Bool {
    if lhs.fileID != rhs.fileID {return false}
    if lhs.chunks != rhs.chunks {return false}
    if lhs.completeHash != rhs.completeHash {return false}
    if lhs.contentType != rhs.contentType {return false}
    if lhs.totalSizeBytes != rhs.totalSizeBytes {return false}
    if lhs.fileName != rhs.fileName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_ChunkInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ChunkInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}index\0\u{3}attachment_id\0\u{3}content_key\0\u{1}nonce\0\u{3}chunk_hash\0\u{3}size_bytes\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.index) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.attachmentID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.contentKey) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.nonce) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.chunkHash) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.sizeBytes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularUInt32Field(value: self.index, fieldNumber: 1)
    }
    if !self.attachmentID.isEmpty {
      try visitor.visitSingularStringField(value: self.attachmentID, fieldNumber: 2)
    }
    if !self.contentKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.contentKey, fieldNumber: 3)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.nonce, fieldNumber: 4)
    }
    if !self.chunkHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.chunkHash, fieldNumber: 5)
    }
    if self.sizeBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.sizeBytes, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_ChunkInfo, rhs: Obscura_V2_ChunkInfo) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.attachmentID != rhs.attachmentID {return false}
    if lhs.contentKey != rhs.contentKey {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.chunkHash != rhs.chunkHash {return false}
    if lhs.sizeBytes != rhs.sizeBytes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_ModelSync: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ModelSync"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}model\0\u{1}id\0\u{1}op\0\u{1}timestamp\0\u{1}data\0\u{1}signature\0\u{3}author_device_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.op) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.authorDeviceID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 1)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 2)
    }
    if self.op != .unspecified {
      try visitor.visitSingularEnumField(value: self.op, fieldNumber: 3)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 4)
    }
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 5)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 6)
    }
    if !self.authorDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.authorDeviceID, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_ModelSync, rhs: Obscura_V2_ModelSync) -> Bool {
    if lhs.model != rhs.model {return false}
    if lhs.id != rhs.id {return false}
    if lhs.op != rhs.op {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.data != rhs.data {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.authorDeviceID != rhs.authorDeviceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V2_ModelSync.Op: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0OP_UNSPECIFIED\0\u{1}OP_UPDATE\0\u{1}OP_DELETE\0\u{1}OP_CREATE\0")
}

extension Obscura_V2_ModelSignal: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ModelSignal"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}model\0\u{1}kind\0\u{3}context_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.contextID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 1)
    }
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if !self.contextID.isEmpty {
      try visitor.visitSingularStringField(value: self.contextID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V2_ModelSignal, rhs: Obscura_V2_ModelSignal) -> Bool {
    if lhs.model != rhs.model {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.contextID != rhs.contextID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
