// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: obscura.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Obscura_V1_SendMessageRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var messages: [Obscura_V1_SendMessageRequest.Submission] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct Submission: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Client-generated UUID (16 bytes)
    var submissionID: Data = Data()

    /// UUID of the target device (16 bytes)
    var deviceID: Data = Data()

    /// The encrypted message payload
    var message: Data = Data()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

struct Obscura_V1_SendMessageResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// If empty, all submissions in the batch were successfully queued.
  var failedSubmissions: [Obscura_V1_SendMessageResponse.FailedSubmission] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum ErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0

    /// Device not found in database
    case invalidDevice // = 1

    /// Device ID bytes are invalid (expected 16)
    case malformedDeviceID // = 2

    /// Submission ID bytes are invalid (expected 16)
    case malformedSubmissionID // = 3

    /// Message payload is missing
    case messageMissing // = 4
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .invalidDevice
      case 2: self = .malformedDeviceID
      case 3: self = .malformedSubmissionID
      case 4: self = .messageMissing
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .invalidDevice: return 1
      case .malformedDeviceID: return 2
      case .malformedSubmissionID: return 3
      case .messageMissing: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Obscura_V1_SendMessageResponse.ErrorCode] = [
      .unspecified,
      .invalidDevice,
      .malformedDeviceID,
      .malformedSubmissionID,
      .messageMissing,
    ]

  }

  struct FailedSubmission: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Echoed back to the client (16 bytes)
    var submissionID: Data = Data()

    var errorCode: Obscura_V1_SendMessageResponse.ErrorCode = .unspecified

    /// Optional human-readable context
    var errorMessage: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

/// The top-level frame exchanged over the WebSocket connection.
struct Obscura_V1_WebSocketFrame: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var payload: Obscura_V1_WebSocketFrame.OneOf_Payload? = nil

  /// Client -> Server: Acknowledge receipt of a message and triggers server-side deletion.
  var ack: Obscura_V1_AckMessage {
    get {
      if case .ack(let v)? = payload {return v}
      return Obscura_V1_AckMessage()
    }
    set {payload = .ack(newValue)}
  }

  /// Server -> Client: Notification that one-time pre-keys are running low.
  var preKeyStatus: Obscura_V1_PreKeyStatus {
    get {
      if case .preKeyStatus(let v)? = payload {return v}
      return Obscura_V1_PreKeyStatus()
    }
    set {payload = .preKeyStatus(newValue)}
  }

  /// Server -> Client: Batch of messages delivered in a single frame.
  var envelopeBatch: Obscura_V1_EnvelopeBatch {
    get {
      if case .envelopeBatch(let v)? = payload {return v}
      return Obscura_V1_EnvelopeBatch()
    }
    set {payload = .envelopeBatch(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Payload: Equatable, Sendable {
    /// Client -> Server: Acknowledge receipt of a message and triggers server-side deletion.
    case ack(Obscura_V1_AckMessage)
    /// Server -> Client: Notification that one-time pre-keys are running low.
    case preKeyStatus(Obscura_V1_PreKeyStatus)
    /// Server -> Client: Batch of messages delivered in a single frame.
    case envelopeBatch(Obscura_V1_EnvelopeBatch)

  }

  init() {}
}

/// Sent by client to confirm processing. Server deletes the message upon receipt.
struct Obscura_V1_AckMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// UUIDs of the messages to acknowledge (16 bytes each).
  var messageIds: [Data] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Obscura_V1_PreKeyStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var oneTimePreKeyCount: Int32 = 0

  /// The server's configured threshold
  var minThreshold: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A batch of envelopes for bulk message delivery over WebSocket.
/// Server -> Client: Multiple messages delivered in a single frame.
struct Obscura_V1_EnvelopeBatch: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var envelopes: [Obscura_V1_Envelope] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Represents a message waiting in the queue for the connected device.
/// The client MUST reply with an `AckMessage` containing this message's ID.
struct Obscura_V1_Envelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// UUID of the message (16 bytes).
  var id: Data = Data()

  /// UUID of the sender (16 bytes).
  var senderID: Data = Data()

  /// Server-generated timestamp (ms) of when the message was received.
  var timestamp: UInt64 = 0

  /// The encrypted message payload
  var message: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "obscura.v1"

extension Obscura_V1_SendMessageRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SendMessageRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}messages\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.messages) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.messages.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.messages, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V1_SendMessageRequest, rhs: Obscura_V1_SendMessageRequest) -> Bool {
    if lhs.messages != rhs.messages {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V1_SendMessageRequest.Submission: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Obscura_V1_SendMessageRequest.protoMessageName + ".Submission"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}submission_id\0\u{3}device_id\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.submissionID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.submissionID.isEmpty {
      try visitor.visitSingularBytesField(value: self.submissionID, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularBytesField(value: self.deviceID, fieldNumber: 2)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularBytesField(value: self.message, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V1_SendMessageRequest.Submission, rhs: Obscura_V1_SendMessageRequest.Submission) -> Bool {
    if lhs.submissionID != rhs.submissionID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V1_SendMessageResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SendMessageResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}failed_submissions\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.failedSubmissions) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.failedSubmissions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.failedSubmissions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V1_SendMessageResponse, rhs: Obscura_V1_SendMessageResponse) -> Bool {
    if lhs.failedSubmissions != rhs.failedSubmissions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V1_SendMessageResponse.ErrorCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ERROR_CODE_UNSPECIFIED\0\u{1}ERROR_CODE_INVALID_DEVICE\0\u{1}ERROR_CODE_MALFORMED_DEVICE_ID\0\u{1}ERROR_CODE_MALFORMED_SUBMISSION_ID\0\u{1}ERROR_CODE_MESSAGE_MISSING\0")
}

extension Obscura_V1_SendMessageResponse.FailedSubmission: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Obscura_V1_SendMessageResponse.protoMessageName + ".FailedSubmission"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}submission_id\0\u{3}error_code\0\u{3}error_message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.submissionID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.errorCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.submissionID.isEmpty {
      try visitor.visitSingularBytesField(value: self.submissionID, fieldNumber: 1)
    }
    if self.errorCode != .unspecified {
      try visitor.visitSingularEnumField(value: self.errorCode, fieldNumber: 2)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V1_SendMessageResponse.FailedSubmission, rhs: Obscura_V1_SendMessageResponse.FailedSubmission) -> Bool {
    if lhs.submissionID != rhs.submissionID {return false}
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V1_WebSocketFrame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WebSocketFrame"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{b}ack\0\u{3}pre_key_status\0\u{3}envelope_batch\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 11: try {
        var v: Obscura_V1_AckMessage?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .ack(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .ack(v)
        }
      }()
      case 12: try {
        var v: Obscura_V1_PreKeyStatus?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .preKeyStatus(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .preKeyStatus(v)
        }
      }()
      case 13: try {
        var v: Obscura_V1_EnvelopeBatch?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .envelopeBatch(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .envelopeBatch(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .ack?: try {
      guard case .ack(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .preKeyStatus?: try {
      guard case .preKeyStatus(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .envelopeBatch?: try {
      guard case .envelopeBatch(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V1_WebSocketFrame, rhs: Obscura_V1_WebSocketFrame) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V1_AckMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AckMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}message_ids\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedBytesField(value: &self.messageIds) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.messageIds.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.messageIds, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V1_AckMessage, rhs: Obscura_V1_AckMessage) -> Bool {
    if lhs.messageIds != rhs.messageIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V1_PreKeyStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PreKeyStatus"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}one_time_pre_key_count\0\u{3}min_threshold\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.oneTimePreKeyCount) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.minThreshold) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.oneTimePreKeyCount != 0 {
      try visitor.visitSingularInt32Field(value: self.oneTimePreKeyCount, fieldNumber: 1)
    }
    if self.minThreshold != 0 {
      try visitor.visitSingularInt32Field(value: self.minThreshold, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V1_PreKeyStatus, rhs: Obscura_V1_PreKeyStatus) -> Bool {
    if lhs.oneTimePreKeyCount != rhs.oneTimePreKeyCount {return false}
    if lhs.minThreshold != rhs.minThreshold {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V1_EnvelopeBatch: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EnvelopeBatch"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}envelopes\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.envelopes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.envelopes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.envelopes, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V1_EnvelopeBatch, rhs: Obscura_V1_EnvelopeBatch) -> Bool {
    if lhs.envelopes != rhs.envelopes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Obscura_V1_Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Envelope"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}sender_id\0\u{1}timestamp\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.senderID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularBytesField(value: self.id, fieldNumber: 1)
    }
    if !self.senderID.isEmpty {
      try visitor.visitSingularBytesField(value: self.senderID, fieldNumber: 2)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 3)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularBytesField(value: self.message, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Obscura_V1_Envelope, rhs: Obscura_V1_Envelope) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.senderID != rhs.senderID {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
